name: oru_rock
description: FrontApp With Flutter

version: 1.0.0+10004

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  logger: ^1.1.0
  get_storage: ^2.0.3
  intl: ^0.17.0
  permission_handler: ^10.2.0
  #UI
  shadow: ^1.5.0
  animated_text_kit: ^4.2.2
  flutter_image_slideshow: ^0.1.4
  bottom_sheet: ^3.1.2
  flutter_toggle_tab: ^1.2.0
  animations: ^2.0.7
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.0.0

  flutter_naver_map:
    git: https://github.com/note11g/flutter_naver_map.git
  google_mobile_ads: ^2.0.1
  # Login
  kakao_flutter_sdk: ^1.3.0-beta.4 # 카카오 로그인
  firebase_auth: ^4.1.0
  google_sign_in: ^5.4.1
  flutter_signin_button: ^2.0.0
  sign_in_with_apple: ^4.1.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.4 # splah(첫 로고 화면)용 library
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/image/logo/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/image/
    - asset/image/logo/
    - asset/image/icon/

  fonts:
      # NotoSans-KR
    - family: NotoB
      fonts:
        - asset: asset/font/Noto_Sans_KR/NotoSansKR-Bold.otf
    - family: NotoL
      fonts:
        - asset: asset/font/Noto_Sans_KR/NotoSansKR-Light.otf
    - family: NotoM
      fonts:
        - asset: asset/font/Noto_Sans_KR/NotoSansKR-Medium.otf
    - family: NotoR
      fonts:
        - asset: asset/font/Noto_Sans_KR/NotoSansKR-Regular.otf
    - family: NotoT
      fonts:
        - asset: asset/font/Noto_Sans_KR/NotoSansKR-Thin.otf
      # NanumSquare
    - family: NanumB
      fonts:
        - asset: asset/font/nanum-square/NanumSquareB.otf
    - family: NanumEB
      fonts:
        - asset: asset/font/nanum-square/NanumSquareEB.otf
    - family: NanumL
      fonts:
        - asset: asset/font/nanum-square/NanumSquareL.otf
    - family: NanumR
      fonts:
        - asset: asset/font/nanum-square/NanumSquareR.otf
    - family: NanumACB
      fonts:
        - asset: asset/font/nanum-square/NanumSquareOTF_acB.otf
    - family: NanumACEB
      fonts:
        - asset: asset/font/nanum-square/NanumSquareOTF_acEB.otf
    - family: NanumACL
      fonts:
        - asset: asset/font/nanum-square/NanumSquareOTF_acL.otf
    - family: NanumACR
      fonts:
        - asset: asset/font/nanum-square/NanumSquareOTF_acR.otf